apiVersion: v2
dependencies:
- condition: utils-templates.enabled
  name: utils-templates
  repository: ""
description: A Helm chart to deploy common resources for the Gardener runtime and
  application
name: utils-common
version: 1.70.1
