apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-management-base-values
  namespace: flux-system
data:
  values.yaml: |-
    createCRDs:
      issuers: false
      certificates: false
    configuration:
      defaultIssuer: default-issuer
      defaultIssuerDomainRanges: >-
        {{- (print .Values.gardenlet.ingressDomain "." .Values.domains.global.domain) | nindent 8 }}
      certClass: base-cert-class
      issuerNamespace: garden
      dnsClass: base-dns-class
      dnsNamespace: garden
