apiVersion: v1
kind: Secret
metadata:
  name: external-dns-management-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
{{- if .Values.registryOverwrite }}
    image:
      repository: {{ include "replaceRegistry" (dict "eu.gcr.io/gardener-project/dns-controller-manager" .Values.registryOverwrite) }}
{{- end }}
    external-dns-management: # !!!!!!!!!!!!!!!!
      enabled: true
      configuration:
        dnsClass: base-dns-class
        identifier: {{ .Values.clusterIdentity }}-base-dns
