apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    controller:
      service:
        annotations:
          cert.gardener.cloud/class: base-cert-class
          cert.gardener.cloud/secretname: controlplane-cert-secret
          dns.gardener.cloud/dnsnames: >-
            {{- (print "*." .Values.gardenlet.ingressDomain "." .Values.domains.global.domain) | nindent 12 }}
          dns.gardener.cloud/ttl: "600"
          dns.gardener.cloud/class: base-dns-class
      extraArgs:
        enable-ssl-passthrough: ""
