global:
    enableOverlayAsDefaultForCalico: true
    enableOverlayAsDefaultForCilium: true
    healthPort: 8081
    image:
        pullPolicy: IfNotPresent
        repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/admission-openstack
        tag: v1.41.2
    kubeconfig: null
    metricsPort: 8080
    replicaCount: 1
    resources: {}
    service:
        topologyAwareRouting:
            enabled: false
    serviceAccountTokenVolumeProjection:
        audience: ""
        enabled: false
        expirationSeconds: 43200
    virtualGarden:
        enabled: false
        user:
            name: ""
    vpa:
        enabled: true
        resourcePolicy:
            minAllowed:
                memory: 64Mi
        updatePolicy:
            updateMode: Auto
    webhookConfig:
        serverPort: 10250
