apiVersion: v2
dependencies:
- condition: utils-templates.enabled
  name: utils-templates
  repository: ""
description: A Helm chart to deploy the terminal-controller-manager application related
  components
name: terminal-controller-manager-application
version: 0.35.0
