apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - garden-etcd.yaml
  - garden-extensions.yaml
  - garden-gardener-admission-controller.yaml
  - garden-gardener-apiserver.yaml
  - garden-gardener-controller-manager.yaml
  - garden-gardener-dashboard.yaml
  - garden-gardener-scheduler.yaml
  - garden-gardenlet.yaml
  - garden-identity.yaml
  - garden-kube-apiserver.yaml
  - garden-gardener-metrics-exporter.yaml
  - garden-terminal-controller.yaml
