sources:
- name: gardenlet
  repo: gardener/gardener
  version:
    fromFile: ../../../gardener/gardenlet.yaml
  imageVector: imagevector/containers.yaml
- name: etcd-druid
  repo: gardener/etcd-druid
  version:
    fromFile: iterative
  imageVector: internal/images/images.yaml
- name: provider-openstack
  repo: gardener/gardener-extension-provider-openstack
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: provider-azure
  repo: gardener/gardener-extension-provider-azure
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: provider-aws
  repo: gardener/gardener-extension-provider-aws
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: provider-gcp
  repo: gardener/gardener-extension-provider-gcp
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: provider-alicloud
  repo: gardener/gardener-extension-provider-alicloud
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: provider-hcloud
  repo: 23technologies/gardener-extension-provider-hcloud
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: charts/images.yaml
- name: networking-calico
  repo: gardener/gardener-extension-networking-calico
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: networking-cilium
  repo: gardener/gardener-extension-networking-cilium
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-cert-service
  repo: gardener/gardener-extension-shoot-cert-service
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-dns-service
  repo: gardener/gardener-extension-shoot-dns-service
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: charts/images.yaml
- name: runtime-gvisor
  repo: gardener/gardener-extension-runtime-gvisor
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-oidc-service
  repo: gardener/gardener-extension-shoot-oidc-service
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-networking-filter
  repo: gardener/gardener-extension-shoot-networking-filter
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-networking-problemdetector
  repo: gardener/gardener-extension-shoot-networking-problemdetector
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
- name: shoot-rsyslog-relp
  repo: gardener/gardener-extension-shoot-rsyslog-relp
  version:
    fromFile: ../../../configuration/configuration/templates/extensions.yaml
  imageVector: imagevector/images.yaml
