apiVersion: v1
kind: Secret
metadata:
  name: identity-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    staticPasswords:
    - email: dev@local.gardener.cloud
      hash: $2a$10${DOLLAR}eWNJshWJxf24FVm4u7W1XOYiPzdSscmFgs3GVF.PYaC42DjuX1piu
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
