apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: application.enabled
  name: application
  repository: ""
- condition: runtime.enabled
  name: runtime
  repository: ""
description: A Helm chart for the Gardener Openstack admission controller
name: gardener-extension-admission-openstack
version: 1.42.1
