apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-management-base-values
  namespace: flux-system
data:
  values.yaml: |-
    configuration:
      defaultIssuer: default-issuer
      defaultIssuerDomainRanges: ${GARDENLET_INGRESS:=internal}.${ENV}.${BASE_DOMAIN}
      certClass: base-cert-class
      issuerNamespace: garden
      dnsClass: base-dns-class
      dnsNamespace: garden
