apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gardener-configuration
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: gardener/configuration
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: 23ke
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: 23ke-config-0
      optional: true
    - kind: Secret
      name: 23ke-config-1
      optional: true
    - kind: Secret
      name: 23ke-config-2
      optional: true
    - kind: Secret
      name: 23ke-config
      optional: true
