apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudprofiles.yaml
  - configuration.yaml
  - dashboard.yaml
  - etcd.yaml
  - etcd-events.yaml
  - extensions.yaml
  - gardener.yaml
  - gardenlet.yaml
  - gardener-metrics-exporter.yaml
  - identity.yaml
  - kube-apiserver.yaml
  - pre-gardenlet.yaml
  - priorityclasses.yaml
