apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: runtime.enabled
  name: runtime
  repository: ""
- condition: application.enabled
  name: application
  repository: ""
description: A Helm chart for the Gardener GCP gardener-extension-admission-gcp
name: gardener-extension-admission-gcp
version: 1.38.0
