apiVersion: v2
dependencies:
- condition: utils-common.enabled
  name: utils-common
  repository: ""
- condition: utils-templates.enabled
  name: utils-templates
  repository: ""
description: A Helm chart to deploy the Gardener runtime related resources
name: runtime
version: 1.66.3
