apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: application.enabled
  name: application
  repository: ""
- condition: runtime.enabled
  name: runtime
  repository: ""
description: A Helm chart for the Gardener AWS admission controller
name: gardener-extension-admission-aws
version: 1.57.1
