application:
    enabled: false
global:
    healthPort: 8081
    image:
        pullPolicy: IfNotPresent
        repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/admission-alicloud
        tag: v1.55.0
    kubeconfig: null
    metricsPort: 8080
    replicaCount: 1
    resources: {}
    service:
        topologyAwareRouting:
            enabled: false
    serviceAccountTokenVolumeProjection:
        audience: ""
        enabled: false
        expirationSeconds: 43200
    virtualGarden:
        enabled: true
        user:
            name: ""
    vpa:
        enabled: true
        resourcePolicy:
            minAllowed:
                memory: 64Mi
        updatePolicy:
            updateMode: Auto
    webhookConfig:
        serverPort: 10250
runtime:
    enabled: false
